# Generated by Django 5.2.1 on 2025-06-07 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones_medicas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.TextField()),
                ('contacto', models.CharField(max_length=100)),
                ('historial_clinico', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('numero_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='doctores/perfiles/')),
                ('google_account', models.EmailField(blank=True, max_length=255, null=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_push', models.BooleanField(default=True)),
                ('notificaciones_sonido', models.BooleanField(default=True)),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='light', max_length=20)),
                ('color_principal', models.CharField(default='#2b4c7e', max_length=7)),
                ('animaciones_activas', models.BooleanField(default=True)),
                ('calidad_imagen', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='high', max_length=10)),
                ('pacientes_atendidos', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='core.doctorprofile'),
        ),
        migrations.CreateModel(
            name='ImagenDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.FileField(upload_to='imagenes/originales/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'dcm'])])),
                ('imagen_procesada', models.FileField(blank=True, null=True, upload_to='imagenes/procesadas/%Y/%m/%d/')),
                ('gradcam', models.FileField(blank=True, null=True, upload_to='imagenes/gradcam/%Y/%m/%d/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='InformePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='informes/')),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.diagnostico')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='core.paciente'),
        ),
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_principal', models.CharField(max_length=100)),
                ('tipo_diagnostico', models.CharField(choices=[('normal', 'Normal'), ('neumonia_viral', 'Neumonía Viral'), ('neumonia_bacteriana', 'Neumonía Bacteriana'), ('otros', 'Otros')], max_length=30)),
                ('confianza', models.FloatField()),
                ('hallazgos', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('areas_afectadas', models.JSONField(blank=True, null=True)),
                ('severidad', models.CharField(blank=True, max_length=50, null=True)),
                ('coordenadas_roi', models.JSONField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('tiempo_procesamiento', models.FloatField(blank=True, null=True)),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_ia', to='core.imagendiagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valida', models.BooleanField()),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_retroalimentacion', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.diagnostico')),
            ],
        ),
    ]
